-- NovaCare Database Schema
-- Run this script in Oracle SQL Developer to create the necessary tables

-- 1. SPECIALIZATION
CREATE TABLE SPECIALIZATION (
    SPECIALIZATIONID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SPECIALIZATIONTYPE VARCHAR2(100) NOT NULL,
    SPEC_DESC VARCHAR2(255)
);

-- 2. ROLES
CREATE TABLE ROLES (
    ROLEID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROLENAME VARCHAR2(50) NOT NULL,
    ROLEDESCRIPTION VARCHAR2(255)
);

-- 3. ROOMS
CREATE TABLE ROOMS (
    ROOMID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ROOMTYPE VARCHAR2(100) NOT NULL,
    AVAILABILITYSTATUS VARCHAR2(50) NOT NULL
);

-- 4. STAFF
CREATE TABLE STAFF (
    STAFFID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRSTNAME VARCHAR2(100) NOT NULL,
    LASTNAME VARCHAR2(100) NOT NULL,
    ROLEID NUMBER NOT NULL,
    PHONENUM VARCHAR2(20),
    EMAIL VARCHAR2(255) UNIQUE,
    HIREDATE DATE,
    SHIFT VARCHAR2(20),
    FOREIGN KEY (ROLEID) REFERENCES ROLES(ROLEID)
);

-- 5. DOCTORS
CREATE TABLE DOCTORS (
    DOCTORID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FIRSTNAME VARCHAR2(100) NOT NULL,
    LASTNAME VARCHAR2(100) NOT NULL,
    SPECIALIZATIONID NUMBER NOT NULL,
    EMAIL VARCHAR2(255) NOT NULL UNIQUE,
    PHONENUM VARCHAR2(20) NOT NULL,
    LICENSENUM VARCHAR2(50) NOT NULL UNIQUE,
    STATUS VARCHAR2(20) NOT NULL,
    FOREIGN KEY (SPECIALIZATIONID) REFERENCES SPECIALIZATION(SPECIALIZATIONID)
);

-- 6. PATIENTS
CREATE TABLE PATIENTS (
    PATIENTIC VARCHAR2(20) PRIMARY KEY,
    FIRSTNAME VARCHAR2(100) NOT NULL,
    LASTNAME VARCHAR2(100) NOT NULL,
    DATEOFBIRTH DATE NOT NULL,
    GENDER CHAR(1) CHECK (GENDER IN ('M','F')),
    PHONENUM VARCHAR2(20),
    EMAIL VARCHAR2(255),
    ADDRESS VARCHAR2(255),
    EMERGENCYCONTACT VARCHAR2(20),
    BLOODTYPE VARCHAR2(5),
    ALLERGIES VARCHAR2(255)
);

-- 7. MEDICINE
CREATE TABLE MEDICINE (
    MEDICINEID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MEDNAME VARCHAR2(100) NOT NULL,
    MEDPOSTINGDATE DATE NOT NULL,
    MEDEXPIRYDATE DATE NOT NULL,
    MEDDOSAGEFORM VARCHAR2(50),
    MEDDESCRIPTION VARCHAR2(255),
    MEDPRICE NUMBER(8,2) NOT NULL,
    CURRENTSTOCK NUMBER NOT NULL,
    MANUFACTURER VARCHAR2(100),
    SIDEEFFECTS VARCHAR2(255)
);

-- 8. APPOINTMENTS
CREATE TABLE APPOINTMENTS (
    APPOINTMENTID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STAFFID NUMBER NOT NULL,
    PATIENTIC VARCHAR2(20) NOT NULL,
    DOCTORID NUMBER NOT NULL,
    ROOMID NUMBER NOT NULL,
    APPOINTMENTDATE DATE NOT NULL,
    APPOINTMENTTIME VARCHAR2(10) NOT NULL,
    REASONTOVISIT VARCHAR2(255),
    STATUS VARCHAR2(20),
    FOREIGN KEY (STAFFID) REFERENCES STAFF(STAFFID),
    FOREIGN KEY (PATIENTIC) REFERENCES PATIENTS(PATIENTIC),
    FOREIGN KEY (DOCTORID) REFERENCES DOCTORS(DOCTORID),
    FOREIGN KEY (ROOMID) REFERENCES ROOMS(ROOMID)
);

-- 9. MEDICAL RECORDS
CREATE TABLE MEDICALRECORD (
    RECORDID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APPOINTMENTID NUMBER NOT NULL,
    VISITDATE DATE NOT NULL,
    SYMPTOM VARCHAR2(255),
    DIAGNOSIS VARCHAR2(255),
    FOREIGN KEY (APPOINTMENTID) REFERENCES APPOINTMENTS(APPOINTMENTID)
);

-- 10. PRESCRIPTIONS
CREATE TABLE PRESCRIPTION (
    PRESCRIPTIONID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RECORDID NUMBER NOT NULL,
    INSTRUCTION VARCHAR2(255),
    FOREIGN KEY (RECORDID) REFERENCES MEDICALRECORD(RECORDID)
);

-- 11. PRESCRIPTION ITEMS
CREATE TABLE PRESCRIPTIONITEM (
    PRESCRIPTIONITEMID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PRESCRIPTIONID NUMBER NOT NULL,
    MEDICINEID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    DOSAGE VARCHAR2(100),
    DATEPRESCRIBED DATE NOT NULL,
    FOREIGN KEY (PRESCRIPTIONID) REFERENCES PRESCRIPTION(PRESCRIPTIONID),
    FOREIGN KEY (MEDICINEID) REFERENCES MEDICINE(MEDICINEID)
);

-- 12. INVOICES
CREATE TABLE INVOICE (
    INVOICEID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APPOINTMENTID NUMBER NOT NULL,
    TOTALAMOUNT NUMBER(10,2) NOT NULL,
    PAYMENTMETHOD VARCHAR2(50),
    DATEPAID DATE,
    FOREIGN KEY (APPOINTMENTID) REFERENCES APPOINTMENTS(APPOINTMENTID)
);

COMMIT;

-- Verify the tables were created
SELECT * FROM DOCTORS;
SELECT * FROM SPECIALIZATION;
SELECT * FROM ROLES;
SELECT * FROM ROOMS;
SELECT * FROM STAFF;
SELECT * FROM PATIENTS;
SELECT * FROM MEDICINE;
SELECT * FROM APPOINTMENTS;
SELECT * FROM MEDICALRECORD;
SELECT * FROM PRESCRIPTION;
SELECT * FROM PRESCRIPTIONITEM;
SELECT * FROM INVOICE;
